# Generated by Django 5.2 on 2025-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
